### ISSUE TITLE
Creating cluster creates error

### ISSUE THREAD

**Issue by kmindspark** [hydro-project/cloudburst#55]
```
python3 -m hydro.cluster.create_cluster -m 1 -r 1 -f 1 -s 1
Creating cluster object...
Adding general instance group
Creating cluster on AWS...
Validating cluster...
Creating management pods...
Creating 1 routing nodes...
Adding 1 routing server node(s) to cluster...
Validating cluster...
Creating 1 memory, 0 ebs node(s)...
Adding 1 memory server node(s) to cluster...
Adding 0 ebs server node(s) to cluster...
Validating cluster...
Creating routing service...
Adding 1 scheduler nodes...
Adding 1 scheduler server node(s) to cluster...
Validating cluster...
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/websocket/_http.py", line 143, in _get_addrinfo_list
    hostname, port, 0, 0, socket.SOL_TCP)
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/stream/ws_client.py", line 253, in websocket_call
    client = WSClient(configuration, get_websocket_url(url), headers)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/stream/ws_client.py", line 76, in __init__
    self.sock.connect(url, header=header)
  File "/usr/local/lib/python3.6/dist-packages/websocket/_core.py", line 223, in connect
    options.pop('socket', None))
  File "/usr/local/lib/python3.6/dist-packages/websocket/_http.py", line 113, in connect
    hostname, port, is_secure, proxy)
  File "/usr/local/lib/python3.6/dist-packages/websocket/_http.py", line 154, in _get_addrinfo_list
    raise WebSocketAddressException(e)
websocket._exceptions.WebSocketAddressException: [Errno -2] Name or service not known
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/hydro-project/cluster/hydro/cluster/create_cluster.py", line 228, in <module>
    aws_key_id, aws_key)
  File "/home/ubuntu/hydro-project/cluster/hydro/cluster/create_cluster.py", line 124, in create_cluster
    BATCH_SIZE, prefix)
  File "/home/ubuntu/hydro-project/cluster/hydro/cluster/add_nodes.py", line 129, in batch_add_nodes
    prefix)
  File "/home/ubuntu/hydro-project/cluster/hydro/cluster/add_nodes.py", line 116, in add_nodes
    '/hydro/anna/conf/', cname)
  File "/home/ubuntu/hydro-project/cluster/hydro/shared/util.py", line 140, in copy_file_to_pod
    _preload_content=False, container=container)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/stream/stream.py", line 36, in stream
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/apis/core_v1_api.py", line 835, in connect_get_namespaced_pod_exec
    (data) = self.connect_get_namespaced_pod_exec_with_http_info(name, namespace, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/apis/core_v1_api.py", line 935, in connect_get_namespaced_pod_exec_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/api_client.py", line 334, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/client/api_client.py", line 168, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/stream/stream.py", line 31, in _intercept_request_call
    return ws_client.websocket_call(config, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/kubernetes/stream/ws_client.py", line 259, in websocket_call
    raise ApiException(status=0, reason=str(e))
kubernetes.client.rest.ApiException: (0)
Reason: [Errno -2] Name or service not known
```

Running `kubectl get pods` shows that the scheduler pod has crashed. The last few lines of its logs are:
```
Traceback (most recent call last):
  File "cloudburst/server/scheduler/server.py", line 350, in <module>
    sched_conf['policy'])
KeyError: 'policy'
```

**Comment by LunaYin** [comment]
we have the same problem

**Comment by cw75** [comment]
@LunaYin I just pushed a fix. Could you try again? thx.

**Comment by LunaYin** [comment]
> @LunaYin I just pushed a fix. Could you try again? thx.

We can create the cluster successfully now, thanks!
